branches:
  - main
repositoryUrl: 'git@github.com:mrparkers/sparky-test.git'
preset: conventionalcommits
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - path: '@liatrio/semantic-release-helm'
    githubPagesBranch: gh-pages
    charts:
      - charts/sparky
  - path: '@semantic-release/git'
    assets:
      - package.json
      - charts/sparky/Chart.yaml
  - path: '@semantic-release/github'
    failComment: false
    successComment: false
    assets:
      - path: 'sparky-*.tgz'
        label: Helm Chart
