branches:
  - main
repositoryUrl: 'git@github.com:mrparkers/sparky-test.git'
preset: conventionalcommits
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - path: '@liatrio/semantic-release-helm'
    aws:
      region: us-east-1
      bucket: parker-test-helm-repo
      bucketUrl: https://parker-test-helm-repo.s3.us-east-1.amazonaws.com
    charts:
      - charts/sparky
  - path: '@semantic-release/git'
    assets:
      - package.json
      - charts/sparky/Chart.yaml
  - path: '@semantic-release/github'
    failComment: false
    successComment: false
